# Generated by Django 5.2.7 on 2025-10-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_data_mining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(db_index=True, max_length=20, verbose_name='股票代码')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('open', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收盘价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
            ],
            options={
                'verbose_name': '股票日行情',
                'verbose_name_plural': '股票日行情',
                'db_table': 'stock_daily',
                'indexes': [models.Index(fields=['ts_code', 'trade_date'], name='stock_daily_ts_code_d2a1b9_idx')],
                'unique_together': {('ts_code', 'trade_date')},
            },
        ),
    ]
