# Generated by Django 5.2 on 2025-10-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_data_mining', '0002_stockdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='论文标题')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('pdf_file', models.FileField(upload_to='financial_papers/', verbose_name='PDF文件')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '金融论文',
                'verbose_name_plural': '金融论文',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
